### ISSUE TITLE
Facing this issue while training model

### ISSUE THREAD

**Issue by gurudattapatil** [ivan-alles/localizer#2]
```
(py36) (localizer-main-VK8Pfd4G) C:\Users\internship\Desktop\localizer-main>python localizer\train.py models\maps\config.json
Filter "validate" contains 4 data elements
Traceback (most recent call last):
  File "localizer\train.py", line 981, in <module>
    trainer.run()
  File "localizer\train.py", line 374, in run
    self._read_dataset()
  File "localizer\train.py", line 441, in _read_dataset
    total_obj_count_by_cat[obj.category] += 1
KeyError: 1
```

**Comment by gurudattapatil** [comment]
I have made a anno dataset, it fails shows the following error when running

**Comment by gurudattapatil** [comment]
Oh sorry this was my fault as I started labelling from category 1 instead of 0
