### ISSUE TITLE
Unable to predict models

### ISSUE THREAD

**Issue by gurudattapatil** [ivan-alles/localizer#3]
Got this error:
```
(py36) (localizer-main-VK8Pfd4G) C:\Users\internship\Desktop\localizer-main>python localizer\predict_for_images.py models\tools\config.json datasets\tools
2021-08-30 07:56:08.984216: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-30 07:56:09.538818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10815 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0001:00:00.0, compute capability: 3.7
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
2021-08-30 07:56:10.462987: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-08-30 07:56:11.098206: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8202
Traceback (most recent call last):
  File "localizer\predict_for_images.py", line 31, in <module>
    predictions = localizer.predict(image)
  File "C:\Users\internship\Desktop\localizer-main\localizer\predict.py", line 264, in predict
    result = self._model.predict(batch.inputs)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\training.py", line 1751, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\def_function.py", line 760, in _initialize
    *args, **kwds))
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\eager\def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\training.py:1586 predict_function  *
        return step_function(self, iterator)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\training.py:1569 run_step  **
        outputs = model.predict_step(data)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\training.py:1537 predict_step
        return self(x, training=False)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\functional.py:415 call
        inputs, training=training, mask=mask)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\functional.py:550 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\base_layer.py:1044 __call__
        self._set_save_spec(inputs, args, kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\training\tracking\base.py:530 _method_wrapper
        result = method(self, *args, **kwargs)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\base_layer.py:3040 _set_save_spec
        flat_specs = [tf_utils.get_tensor_spec(x) for x in flat_arg]
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\engine\base_layer.py:3040 <listcomp>
        flat_specs = [tf_utils.get_tensor_spec(x) for x in flat_arg]
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\keras\utils\tf_utils.py:467 get_tensor_spec
        spec = tf.TensorSpec(shape=t.shape, dtype=t.dtype, name=name)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\tensor_spec.py:51 __init__
        self._shape = tensor_shape.TensorShape(shape)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\tensor_shape.py:784 __init__
        self._dims = [as_dimension(dims)]
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\tensor_shape.py:729 as_dimension
        return Dimension(value)
    C:\Users\internship\.virtualenvs\localizer-main-VK8Pfd4G\lib\site-packages\tensorflow\python\framework\tensor_shape.py:209 __init__
        .format(value, type(value))), None)
    <string>:3 raise_from


    TypeError: Dimension value must be integer or None or have an __index__ method, got value '<attribute 'shape' of 'numpy.generic' objects>' with type '<class 'getset_descriptor'>'
```

Any ideas why this is occuring?

**Comment by ivan-alles** [comment]
Can it be that you are using grayscale images (RGB is expected)?

**Comment by gurudattapatil** [comment]
Actually i am running the sample program ( the one with tools), it's facing the same problem as well.

**Comment by ivan-alles** [comment]
It is running on my computer. Are you running with the Pipfile from the repo? Which CUDA version do you have? I have 11.0, my log looks different:

2021-08-31 20:06:21.515057: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-08-31 20:06:23.918642: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-08-31 20:06:23.919854: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-08-31 20:06:23.953431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 with Max-Q Design computeCapability: 7.5
coreClock: 1.095GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 357.69GiB/s
2021-08-31 20:06:23.954071: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-08-31 20:06:23.960619: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-08-31 20:06:23.961238: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-08-31 20:06:23.966340: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-08-31 20:06:23.968507: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-08-31 20:06:23.976967: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-08-31 20:06:23.980579: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-08-31 20:06:23.981558: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-08-31 20:06:23.981993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-08-31 20:06:23.982527: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-31 20:06:23.984163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 with Max-Q Design computeCapability: 7.5
coreClock: 1.095GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 357.69GiB/s
2021-08-31 20:06:23.984963: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-08-31 20:06:23.985285: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-08-31 20:06:23.985600: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-08-31 20:06:23.985927: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-08-31 20:06:23.986292: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-08-31 20:06:23.986610: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-08-31 20:06:23.986932: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-08-31 20:06:23.987245: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-08-31 20:06:23.987583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-08-31 20:06:24.556811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-31 20:06:24.557195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-08-31 20:06:24.557383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-08-31 20:06:24.557750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6599 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-08-31 20:06:24.559108: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
2021-08-31 20:06:26.013824: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-08-31 20:06:26.228832: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
.....

**Comment by gurudattapatil** [comment]
I have 11.4, I'll try it with 11.0

**Comment by gurudattapatil** [comment]
I have CUDA VERSION 11.4, I will try it with 11.0 and check if it works.

**Comment by gurudattapatil** [comment]
It worked
```
{
  "dataset": "datasets/maps/dataset.anno",
  "transfer_learning_base": "models/transfer_learning_base/features.tf",
  "pad_to": 32,
  "object_size": 88,
  "background_weight": 0.2,
  "object_weight_sigma_factor": 4,
  "weight_border": 7,
  "validated_training_examples_count": 50000,
  "final_training_examples_count": 25000,
  "training_fraction": 0.8,
  "training_examples_per_batch": 16,
  "training_examples_per_epoch": 5000,
  "training_examples_count_for_mean_computation": 100,
  "data_augmentation_rotation": [
    -0.05,
    0.05
  ],
  "data_augmentation_shear_rotation": [
    -0.05,
    0.05
  ],
  "data_augmentation_shear_scale": [
    0.95,
    1.05
  ],
  "data_augmentation_scale": [
    0.95,
    1.05
  ],
  "data_augmentation_color": [
    0.9,
    1.1
  ],
  "loss_weight_pos": 1,
  "loss_weight_angle": 1,
  "rng_seed": 1,
  "sigma": 1.5,
  "confidence_ksize": 7,
  "angle_ksize": 3,
  "pos_ksize": 3,
  "confidence_thr": 0.5,
  "position_diff_thr": 15,
  "angle_diff_thr": 15,
  "input_scale": 0.7,
  "model_scale": 0.125,
  "input_shape": [
    384,
    384,
    3
  ],
  "random_background_probability": 0.1,
  "process_count": 4
}
```
**This is the config file I used for my own dataset named maps, which is same as the tools program.
But i am facing error**
```
(localizer-main-VK8Pfd4G) (py36) C:\Users\internship\Desktop\localizer-main>python localizer\train.py models\maps\config.json
2021-09-01 10:54:55.122252: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Filter "validate" contains 3 data elements
Filter "train" contains 12 data elements
Traceback (most recent call last):
  File "localizer\train.py", line 981, in <module>
    trainer.run()
  File "localizer\train.py", line 374, in run
    self._read_dataset()
  File "localizer\train.py", line 456, in _read_dataset
    assert np.allclose(1, flt.data_element_weights.sum()), flt_name
AssertionError: train
```
Should there be adjustments in the program?
for reference:
[Maps ML-localizer program](https://github.com/gurudattapatil/mlprogram)

**Comment by ivan-alles** [comment]
This is because you only have 2 objects of category 1, and they all were reserved for validation by random selection. So there is no objects of category 1 for training. Can you add more such objects?

**Comment by gurudattapatil** [comment]
Thank you!

**Comment by trungpham2606** [comment]
Hello @ivan-alles @gurudattapatil 
I dont see the loss for angle prediction. Did I miss something ?
