### ISSUE TITLE
Unable to run the with following images

### ISSUE THREAD

**Issue by gurudattapatil** [ivan-alles/localizer#5]
I am unable to train models using these files.
for reference:[ML program](https://github.com/gurudattapatil/mycode)
Getting the following error:
`(localizer-main-VK8Pfd4G) (py36) C:\Users\internship\Desktop\localizer-main>python localizer\train.py models\maps\config.json
2021-11-16 09:45:50.877785: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Filter "validate" contains 3 data elements
Traceback (most recent call last):
  File "localizer\train.py", line 981, in <module>
    trainer.run()
  File "localizer\train.py", line 374, in run
    self._read_dataset()
  File "localizer\train.py", line 456, in _read_dataset
    assert np.allclose(1, flt.data_element_weights.sum()), flt_name
AssertionError: validate`

is there a particular reason?

**Comment by gurudattapatil** [comment]
Can you try this code on your system? Instead of tools I have used the maps dataset.

**Comment by gurudattapatil** [comment]
The program needed more data

**Comment by gurudattapatil** [comment]
But this error occurs when provided with more data
` ValueError: Dimension 1 in both shapes must be equal, but are 53 and 52. Shapes are [?,53,131] and [?,52,130]. for '{{node model/model/tf.concat/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](model/model/conv2d_7/Relu, model/model/up_sampling2d/resize/ResizeNearestNeighbor, model/model/tf.concat/concat/axis)' with input shapes: [?,53,131,256], [?,52,130,512], [] and with computed input tensors: input[2] = <-1>.`
